import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Book your Inspection",
  description: "Generated by create next app",
  icons: {
    icon: "https://s3.us-west-1.amazonaws.com/prod.us-west-1c.app.zuperpro/attachments/62a6651b-aae2-4f56-a438-5447f073641a/e7184e53-3dcb-4d9f-aa68-c8121f5b0268.png",
    shortcut: "https://s3.us-west-1.amazonaws.com/prod.us-west-1c.app.zuperpro/attachments/62a6651b-aae2-4f56-a438-5447f073641a/e7184e53-3dcb-4d9f-aa68-c8121f5b0268.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
